### PR TITLE
Translation to Czech

### PR DESCRIPTION
**Pull request by PetyXbron**
Added Czech translation!
- **Translated all strings** from [Strings_en.properties](https://github.com/Shabinder/SpotiFlyer/blob/v3.6.1/translations/Strings_en.properties) to new file: [Strings_cs.properties](https://github.com/Shabinder/SpotiFlyer/pull/1072/commits/65f659a865f8bd749f9b991c69f21bb3a25d3d51)
- About **Czech Republic**:
  - [Wikipedia](https://en.wikipedia.org/wiki/Czech_Republic)
  - Language code: `CS`
  - Country code: `CZ`

### CODE REVIEW

**Comment by Shabinder** [comment]
Thanks for your contribution :+1:

**Review by Pafkara — APPROVED** [review]

**Review by Pafkara — APPROVED** [review]

**Review by Pafkara — APPROVED** [review]
Strings_cs.properties

**Review by Pafkara — APPROVED** [review]
translations/Strings_cs.properties

**Review by Pafkara — APPROVED** [review]

**Review by Pafkara — APPROVED** [review]
Cz SpotiFlyer

**Review by Pafkara — APPROVED** [review]

**Pull request merged**
